version: '3.7'

services:
  portail:
    build:
      dockerfile: Dockerfile
      context: .
    image: portail
    container_name: portail
    working_dir: /server
    entrypoint: ["node", "app/server.js"]
    networks:
      - deployement_portail
    ports:
      - "8002:8002"
    environment:
      - ENVIRONMENT_NAME=docker
networks:
  deployement_portail:
    external: true
